### ISSUE TITLE
This project is stolen

### ISSUE THREAD

**Issue by Rainson12** [Sethuramalingam-art/RN-CoffeeShopApp#1]
This project was initally written by @darshanpawar101 https://github.com/darshanpawar101/Coffee-Shop-App/tree/main

**Comment by Sethuramalingam-art** [comment]
> This project was initally written by @darshanpawar101 https://github.com/darshanpawar101/Coffee-Shop-App/tree/main

Hey @Rainson12 I have learnt step by step and see the commits how much time I spent for this. And I am not stole the code, I followed the code step by step for my self learning. Please remove the comment stolen. It is self learning of react native
